version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: my-postgres
    networks:
      - compose-bridge
    environment:
      POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
  
  # alurabooks:
  #   image: aluradocker/alura-books:1.0
  #   container_name: alurabooks
  #   networks:
  #     - compose-bridge
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongodb

networks:
  compose-bridge:
    driver: bridge